import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppContextProvider } from "@/context/AppContext";
import ChatBot from '@/components/ChatBot'; // 1. Bạn đã import ở đây

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shop Laptop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning>
        <AppContextProvider>
          {/* Nội dung chính của trang web */}
          {children}

          {/* 2. Thêm ChatBot vào đây (nằm đè lên trên nội dung nhờ CSS fixed) */}
          <ChatBot />
          
        </AppContextProvider>
      </body>
    </html>
  );
}